# Generated by Django 4.2 on 2023-04-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATCdash', '0003_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
