# Generated by Django 4.2 on 2023-04-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATCdash', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
