# Generated by Django 4.2 on 2023-04-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATCdash', '0006_user_delete_color_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
