# Generated by Django 4.2 on 2023-04-14 16:44

import django.contrib.admin.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('ATCdash', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogEntry',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
    ]
