# Generated by Django 4.2 on 2023-04-15 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATCdash', '0009_userlogentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogEntry',
        ),
    ]
