# Generated by Django 4.2 on 2023-04-15 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATCdash', '0012_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLoginLogout',
        ),
    ]
