# Generated by Django 4.2 on 2023-04-16 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATCdash', '0014_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
